alcohol = {'200111':'Beer and ale',
        '200210':'Whiskey',
        '200310':'Wine',
        '200410':'Other alcoholic beverages',
        '200511':'Beer and ale at fast food, take-out, delivery, concession stands, buffet and cafeteria',
        '200512':'Beer and ale at full service restaurants',
        '200513':'Beer and ale at vending machines and mobile vendors',
        '200514':'Beer at employer',
        '200521':'Wine at fast food, take-out, delivery, concession stands, buffet and cafeteria',
        '200522':'Wine at full service restaurants',
        '200523':'Wine at vending machines and mobile vendors',
        '200524':'Wine at employer',
        '200531':'Other alcoholic beverages at fast food, take-out, delivery, concession stands, buffet and cafeteria',
        '200532':'Other alcoholic beverages at full service restaurants',
        '200533':'Other alcoholic beverages at vending machines and mobile vendors',
        '200534':'Other alcohol at employer'
}
smoking = {'630110':'Cigarettes',
        '630210':'Other tobacco products',
        '630220':'Smoking accessories',
        '630900':'Marijuana'
}
gender = {'SEX2':[None, 'Male','Female'],
          'SEX_REF':[None, 'Reference person is male','Reference person is female']}
occupation = {'OCCULIS1':['Administrator, manager',
                            'Teacher',
                            'Professional',
                            'Administrative support, including clerical',
                            'Sales, retail',
                            'Sales, business goods and services',
                            'Technician',
                            'Protective service',
                            'Private household service',
                            'Other service',
                            'Machine operator, assembler, inspector',
                            'Transportation operator',
                            'Handler, helper, laborer',
                            'Mechanic, repairer, precision production',
                            'Construction, mining',
                            'Farming',
                            'Forestry, fishing, groundskeeping',
                            'Armed forces', 
                          'Unknown'],
              'SHORT_OCC':['manager',
                           'teacher',
                           'professional',
                           'admin',
                           'retail',
                           'sales',
                           'technician',
                           'security',
                           'household',
                           'service',
                           'other service',
                           'machinist',
                           'driver',
                           'laborer',
                           'mechanic',
                           'construction',
                           'farmer',
                           'outdoor',
                           'military',
                          'unknown'],
                'OCCULIS2':['Administrator, manager',
            'Teacher',
            'Professional',
            'Administrative support, including clerical',
            'Sales, retail',
            'Sales, business goods and services',
            'Technician',
            'Protective service',
            'Private household service',
            'Other service',
            'Machine operator, assembler, inspector',
            'Transportation operator',
            'Handler, helper, laborer',
            'Mechanic, repairer, precision production',
            'Construction, mining',
            'Farming',
            'Forestry, fishing, groundskeeping',
            'Armed forces']
                }

meats = {'030110':'Ground beef',
'030210':'Chuck roast',
'030310':'Round roast',
'030410':'Other roast',
'030510':'Round steak',
'030610':'Sirloin steak',
'030710':'Other steak',
'030810':'Other beef',
'040110':'Bacon',
'040210':'Pork chops',
'040310':'Ham canned',
'040410':'Other pork',
'040510':'Sausage',
'040610':'Canned ham',
'050110':'Frankfurters',
'050210':'Bologna, liverwurst, salami',
'050310':'Other lunchmeats',
'050410':'Lamb organ meats',
'050900':'Goat',
'060110':'Fresh frozen whole chicken',
'060210':'Fresh frozen chicken parts',
'060310':'Other poultry',
'070110':'Canned fish seafood',
'070230':'Fresh fish shellfish',
'070240':'Frozen fish shellfish'}

income = {'01':'0-4,999',
'02':'5,000-9,999',
'03':'10,000-14,999',
'04':'15,000-19,999',
'05':'20,000-29,999',
'06':'30,000-39,999',
'07':'40,000-49,999',
'08':'50,000-69,999',
'09':'70,000-89,999',
'10':'90,000-119,999',
'11':'120,000 and over'}

region =['Unknown',
    'Northeast',
'Midwest',
'South',
'West'
        ]

housing = {
    '1':"Homeowner w/ Mortgage",
'2':"Homeowner w/o Mortgage ",
'3':"Homeowner-Mortgage status not reported",
'4':"Renter ",
'5':"Occupied without cash payment",
'6':"Student Housing"
}

refgen = [None,
    'Greatest_gen',
'Silent_gen',
'Baby_boomers',
'Gen_x',
'Millennials',
         ]

marital = [None,
    'Married',
'Widowed',
'Divorced',
'Separated',
'Never_married']

education = {'EDU_00':'No_schooling',
'EDU_10':'Elementary_school',
'EDU_11':'Some_high_school',
'EDU_12':'High_school_graduate',
'EDU_13':'Some_college',
'EDU_14':'Associate_degree',
'EDU_15':'Bachelor_degree',
'EDU_16':'Graduate_degree'
}