alcohol = {'200111':'Beer and ale',
        '200210':'Whiskey',
        '200310':'Wine',
        '200410':'Other alcoholic beverages',
        '200511':'Beer and ale at fast food, take-out, delivery, concession stands, buffet and cafeteria',
        '200512':'Beer and ale at full service restaurants',
        '200513':'Beer and ale at vending machines and mobile vendors',
        '200514':'Beer at employer',
        '200521':'Wine at fast food, take-out, delivery, concession stands, buffet and cafeteria',
        '200522':'Wine at full service restaurants',
        '200523':'Wine at vending machines and mobile vendors',
        '200524':'Wine at employer',
        '200531':'Other alcoholic beverages at fast food, take-out, delivery, concession stands, buffet and cafeteria',
        '200532':'Other alcoholic beverages at full service restaurants',
        '200533':'Other alcoholic beverages at vending machines and mobile vendors',
        '200534':'Other alcohol at employer'
}
smoking = {'630110':'Cigarettes',
        '630210':'Other tobacco products',
        '630220':'Smoking accessories',
        '630900':'Marijuana'
}
gender = {'SEX2':[None, 'Male','Female'],
          'SEX_REF':[None, 'Reference person is male','Reference person is female']}
occupation = {'OCCULIS1':['Administrator, manager',
                            'Teacher',
                            'Professional',
                            'Administrative support, including clerical',
                            'Sales, retail',
                            'Sales, business goods and services',
                            'Technician',
                            'Protective service',
                            'Private household service',
                            'Other service',
                            'Machine operator, assembler, inspector',
                            'Transportation operator',
                            'Handler, helper, laborer',
                            'Mechanic, repairer, precision production',
                            'Construction, mining',
                            'Farming',
                            'Forestry, fishing, groundskeeping',
                            'Armed forces'],
                'OCCULIS2':['Administrator, manager',
            'Teacher',
            'Professional',
            'Administrative support, including clerical',
            'Sales, retail',
            'Sales, business goods and services',
            'Technician',
            'Protective service',
            'Private household service',
            'Other service',
            'Machine operator, assembler, inspector',
            'Transportation operator',
            'Handler, helper, laborer',
            'Mechanic, repairer, precision production',
            'Construction, mining',
            'Farming',
            'Forestry, fishing, groundskeeping',
            'Armed forces']
                }

